@portLink=8010


###

GET http://localhost:{{portLink}} HTTP/1.1


###

GET http://localhost:{{portLink}}/api/tags

###

GET http://localhost:{{portLink}}/api/db


###

POST http://localhost:{{portLink}}/api/generate \
Content-Type: application/json

{
    "model": "my-custom-model",
    "prompt": "Привет, как дела?",
    "stream": false
}

###

# curl -X POST http://localhost:8000/api/generate \
#   -H "Content-Type: application/json" \
#   -d '{
#     "model": "my-custom-model",
#     "prompt": "Расскажи о FastAPI",
#     "stream": true
#   }' \
#   -N



# ###

# curl -X POST http://localhost:8000/api/generate \
#   -H "Content-Type: application/json" \
#   -d '{
#     "model": "my-custom-model",
#     "prompt": "Расскажи о FastAPI",
#     "stream": true
#   }' \
#   -N
